name: flutterbackgroundfetch
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  background_fetch: ^0.5.5
  shared_preferences: ^0.5.7+1
  workmanager: ^0.2.2
  flutter_local_notifications: ^1.4.3
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
